version: 2.1
orbs:
  gor: ory/goreleaser@0.1.38
workflows:
  test:
    jobs:
      - test:
          context: docker-hub-login
  release:
    jobs:
      - release:
          context:
            - docker-hub-login
            - github-login
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
commands:
  install_goreleaser:
    description: "Installs the goreleaser binary to ~/bin"
    parameters:
      version:
        type: string
        default: "v1.7.0"
    steps:
      - run:
          name: Install goreleaser
          command: |
            dlURL="https://github.com/goreleaser/goreleaser/releases/download/<< parameters.version >>/goreleaser_Linux_x86_64.tar.gz"
            curl -sSL $dlURL | $SUDO tar -xz -C ~/bin goreleaser
jobs:
  test:
    docker:
      - image: 'cimg/go:1.18'
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
            - go-mod-v1-{{ checksum "go.mod" }}
            - go-mod-v1
      - run:
          name: Download Dependancies
          command: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg/mod
      - install_goreleaser
      - run:
          name: Run tests
          command: |
            ~/bin/goreleaser release --snapshot --skip-publish --rm-dist
  release:
    docker:
      - image: 'cimg/go:1.18'
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
            - go-mod-v1-{{ checksum "go.mod" }}
            - go-mod-v1
      - run:
          name: Download Dependancies
          command: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg/mod
      - install_goreleaser
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Perform release
          command: |
            ~/bin/goreleaser release --skip-publish
            docker login --username="${CONTEXT_GREMLIN_DOCKER_USERNAME}" --password="${CONTEXT_GREMLIN_DOCKER_PASSWORD}"
            docker build -f Dockerfile.goreleaser -t gremlin/aws-encryption-provider:${CIRCLE_TAG} .
            docker push gremlin/aws-encryption-provider:${CIRCLE_TAG}
