version: 2.1
orbs:
  gor: hubci/goreleaser@2.1.0
workflows:
  main-wf:
    jobs:
      - cache
      - docker_setup:
          context:
            - docker-hub-login
      - gor/release:
          version: 1.7.0
          go-version: '1.18'
          dry-run: true
  release-wf:
    jobs:
      - cache:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - docker_setup:
          context:
            - docker-hub-login
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: 1.7.0
          go-version: '1.18'
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
jobs:
  cache:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
            - go-mod-v1-{{ checksum "go.mod" }}
            - go-mod-v1
      - run:
          name: Download Dependancies
          command: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
  docker_setup:
    machine:
      image: ubuntu-2004:current
    steps:
      - run: |
          docker login -u "${CONTEXT_GREMLIN_DOCKER_USERNAME}" -p "${CONTEXT_GREMLIN_DOCKER_PASSWORD}"
